version: 0.2

phases:
  build:
    commands:
      - REPOLIST=mongo:latest,hashicorp/vault:1.14 
      - |
        echo "- Cloning the following Docker Hub repositories for account ${AWS_ACCOUNT_ID} in region ${AWS_REGION}: ${REPOLIST}"
        for repo in $(echo ${REPOLIST} | sed "s/,/ /g")
        do
          echo " ***** ${repo}"
          docker pull docker.io/${repo}
        done
        echo "- Done pulling, I have these images now"
        docker images
        echo "- Will now login to ECR"
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
        echo "- Will now tag and push the images to ECR"
        for repo in $(echo ${REPOLIST} | sed "s/,/ /g")
        do
          echo " ***** ${repo}"
          docker tag ${repo} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${repo}
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${repo}
        done
        echo "- Done pushing to ECR"